### ISSUE TITLE
Parcel Number

### ISSUE THREAD

**Issue by Martin-1182** [webapix/mygls-sdk#10]
Hi, I'm using the getPrintedLabels method to print multiple parcels. But I can't get to the ParcelNumber I need. I need it so that I can then further check the status of the packages. Can you advise me? WELL THANK YOU

ps: When I call the PrepareLabels () function, parcelID is returned in the response. But parcel number would be more necessary. Thank you

**Comment by Martin-1182** [comment]
```Webapix\GLS\Responses\PrepareLabels {#1489 ▼
  #errorKey: "PrepareLabelsError"
  #parcelList: []
  #data: array:2 [▼
    "ParcelInfoList" => array:1 [▼
      0 => array:2 [▼
        "ClientReference" => null
        "ParcelId" => 79463181
      /**   "ParcelNumber" => ......  */
      ]
    ]
    "PrepareLabelsError" => []
  ]
}
```

**Comment by zsocakave** [comment]
Hi,

Every response has a data() method, it will return the original response data. 
The [PrepareLabels response](https://github.com/webapix/mygls-sdk/wiki/PrepareLabels) also has a parcelInfoList() method, with this method you can access each parcel's data.
The GetPrintedLabels request will return only the pdf labels (this is how the GLS API works).

You can find more information in our [wiki](https://github.com/webapix/mygls-sdk/wiki/Basic-usage).

**Comment by zsocakave** [comment]
I think you should use the [PrintLabels](https://github.com/webapix/mygls-sdk/wiki/PrintLabels) request instead of GetPrintedLabels.

**Comment by Martin-1182** [comment]
Thanks for the reply, I'm using getPrintedLabels to make it possible to add multiple ParcelIds. PrintLabels returns only one package. I can send multiple packages with the PrepareLabels function and download them with the GetPrintedLabels function. This is all ok. Just ParcelInfoList does not contain the parcelNumber that is needed for the GetParcelStatuses function, which we now want to check the status of packages. If it was a single PrintLabels package, it is great to return both parcelId and parcelNumber, but in this case it is a matter of working with multiple packages.

**Comment by Martin-1182** [comment]
```
array:2 [▼
  0 => Webapix\GLS\Models\ParcelInfo {#1501 ▼
    #clientReference: null
    #parcelId: 79466430
  }
  1 => Webapix\GLS\Models\ParcelInfo {#1497 ▼
    #clientReference: null
    #parcelId: 79466431
  }
]
```

**Comment by zsocakave** [comment]
Ok, but what can we do with it? This is the limitation of the GLS API, the PrepareLabels request doesn't have ParcelNumber data. We can't change it. You can [contact with GLS](https://api.mygls.hu/) for more information.

**Comment by Martin-1182** [comment]
Hi I know I watched gls doc. Never mind I didn't mean it in a bad way I was just looking for a solution. I solved it so that I will cron download GetParcelList there are the necessary data. Thank you for your willingness.
