### ISSUE TITLE
Repeated download of labels

### ISSUE THREAD

**Issue by MottlShean** [webapix/mygls-sdk#14]
Repeated download of labels:
- I get an error massage while downloading labels repeatedly: "Parcel label is already generated".
- I get no parcel Id in this error message. That can be problem when downloading bigger amount of labels 

It can happen that user makes mistake or there is a downloading error etc. Repeated download of labels is sometimes necessary. 

How can I download labels repeatedly if needs to download it again? Thanks

`
    private function printPackages(array $packages, ?Shipment $shipment): ?string
    {
        $client = new Client(new HttpClient());
        $request = new GetPrintedLabels();

        foreach ($packages as $package) {
            $request->addParcelId($package);
        }

        /** @var GetPrintedLabelsResponse $response */
        $response = $client->on($this->account)
            ->request($request);

        if ($response->successfull()) {
            return $response->getPdf();
        }

        if ($shipment) {
            $shipment->update(
                [
                    'error_message' => $this->glsErrorsToText($response->errors()),
                ]
            );
        }
        Log::error('printLabel: ' . $this->glsErrorsToText($response->errors()));
        return null;
    }

`

**Comment by zsocakave** [comment]
Hello,

You can download/generate the labels only once, unfortunately MyGLS doesn't support calling GetPrintedLabels multiple times for the same parcel.

**Comment by MottlShean** [comment]
Thanks for fast reaction. Jan
