### ISSUE TITLE
Missing "\" before LogicException

### ISSUE THREAD

**Issue by arwin009** [webapix/mygls-sdk#18]
https://github.com/webapix/mygls-sdk/blob/abc87c34ac3415e0bcf7c02228fb9349268bdf0b/src/Responses/Response.php#L78

https://github.com/webapix/mygls-sdk/blob/abc87c34ac3415e0bcf7c02228fb9349268bdf0b/src/Responses/Response.php#L91

**Comment by zsocakave** [comment]
Thank you for your feedback, we fixed it in 1.7.3
