### ISSUE TITLE
Add return type declaration to implement ArrayAccess interface in PHP 8.1 

### ISSUE THREAD

**Issue by arwin009** [webapix/mygls-sdk#19]
https://github.com/webapix/mygls-sdk/blob/abc87c34ac3415e0bcf7c02228fb9349268bdf0b/src/Responses/Response.php#L51
https://github.com/webapix/mygls-sdk/blob/abc87c34ac3415e0bcf7c02228fb9349268bdf0b/src/Responses/Response.php#L62
https://github.com/webapix/mygls-sdk/blob/abc87c34ac3415e0bcf7c02228fb9349268bdf0b/src/Responses/Response.php#L76
https://github.com/webapix/mygls-sdk/blob/abc87c34ac3415e0bcf7c02228fb9349268bdf0b/src/Responses/Response.php#L89

These methods should have return types declared to be compatible with PHP 8.1:
```
interface ArrayAccess {
    /* Methods */
    public offsetExists(mixed $offset): bool
    public offsetGet(mixed $offset): mixed
    public offsetSet(mixed $offset, mixed $value): void
    public offsetUnset(mixed $offset): void
}
```

**Comment by zsocakave** [comment]
New version released, 2.x now PHP8.1 compatible.

**Comment by arwin009** [comment]
Thank you!
