### ISSUE TITLE
How can I get trackingNr which is printed on label?

### ISSUE THREAD

**Issue by MottlShean** [webapix/mygls-sdk#20]
TrackingNr is generated during label generation (a vertical printed number on label). My customer would like to store trackingNr into our application.
How can I get trackingNr which is printed on label? Is there a sample code? 

Thanks

Jan

**Comment by zsocakave** [comment]
Maybe this helps you?

[https://github.com/webapix/mygls-sdk/wiki/PrintLabels](https://github.com/webapix/mygls-sdk/wiki/PrintLabels)

**Comment by MottlShean** [comment]
Thanks. I already use similar code to generate pdf with labels. I need a function to get generated parcelNumber by ParcelId: getParcelNumber(string $parcelId). Thanks

**Comment by zsocakave** [comment]
If you have a ParcelId, you should have a parcel number too!
You can use the [GetParcelList](https://github.com/webapix/mygls-sdk/wiki/GetParcelList) request to get a parcel list and then filter it by ParcelId.

**Comment by MottlShean** [comment]
Thanks
