### ISSUE TITLE
How to create Multi-package shipping label

### ISSUE THREAD

**Issue by MottlShean** [webapix/mygls-sdk#21]
I have a question how to create Multi-package shipping label. Label contains always "Quantity 1/1". Customer woul like to have:
- 1/3 at first shipment package
- 2/3 at second shipment package
- 3/3 at third shipment package

We do it in the following way creating a parcel for each package:

`    protected function sendShipmentRequest(Client $client, Shipment $shipment): ?array
    {
        $stateSentId = ShipmentState::where('code','=','sent')->value('id');
        $request = new PrepareLabels();

        // add all shipment packages
        for ($i = 1; $i <= $shipment->quantity; $i++) {
            // Cash On Delivery pouze pri prvnim balicku
            $request->addParcel($this->getParcel($shipment, $i == 1));
        }        
    }    
`

**How can we create a shipment (parcel) contaning more packages?** 

Thanks for help
   
![label](https://user-images.githubusercontent.com/105339556/207607004-0fe81bc8-d91d-4fe5-a43e-bead682b65fd.jpg)

Jan Mottl
Shean sro

**Comment by zsocakave** [comment]
Parcel object has a "setCount" method, with this method you can set the number of packages sent in one shipment (the default value is 1).

`$parcel->setCount(3);`

**Comment by MottlShean** [comment]
Thanks
