### ISSUE TITLE
Csomagautomatás csomagfeladás

### ISSUE THREAD

**Issue by juhaszraymond** [webapix/mygls-sdk#22]
Sziasztok,

Kerestem a leírásban de nem találtam sehol, hogy lehetséges csomagautomatába/csomagpontra csomagot küldeni?

Előre is köszönöm a segítséget!

**Comment by zsocakave** [comment]
Szia!

Igen, ez a PSD Service (erre van kiemelés a wiki-ben, hogy ebben az esetben is kötelező volt megadni szállítási címet, sajnos a GLS pár dolgot elég furcsán kezel....).

Így:

`(new Parcel)
.....
->when($order->isPSD(), function (Parcel $parcel) use ($order) {
                return $parcel->addService(
                    new ParcelShopDelivery($order->pickup_point_id)
                );
            });`

**Comment by juhaszraymond** [comment]
Ezt a hibát kaptam:
Invalid service parameter, Service 'PSD'

Én így próbáltam a minta kódba beilleszteni:

$parcel = (new \Webapix\GLS\Models\Parcel())
  ->setClientReference('order-2')
   ->setClientNumber('100000004')
   ->setDeliveryInfo($deliveryAddress)
   ->setPickupAddress($pickupAddress)
   ->setContent('Parcel info printed on label.')
   ->addService(new \Webapix\GLS\Services\ParcelShopDelivery("2351-CSOMAGPONT"));

**Comment by zsocakave** [comment]
Szerintem jól csináltad, nem látok benne hibát. Az adott client number olyan régióban van, mint a csomagpont?

Korábban használtuk így és működött, szerintem a hiba a csomagpont azonosítóra vonatkozik.

A hivatalos példa kódban is ugyan így néz ki:

$service1 = new StdClass();

$service1->Code = "PSD";
$parameter1 = new StdClass();
$parameter1->StringValue = "2351-CSOMAGPONT";
$service1->PSDParameter = $parameter1;

**Comment by juhaszraymond** [comment]
Igen, az a furcsa, hogy az általuk adott kód alapján elfogadja. Ugyanazokkal az adatokkal :/ Nem értem mi lehet a probélma.

Elérhető example kódot szerettem volna ennyivel kiegészíteni de sajnos nem megy :/ 

<?php
error_reporting(E_ERROR | E_WARNING | E_PARSE | E_NOTICE);
require __DIR__ . '/vendor/autoload.php';


//You need an account to use the GLS API.
//You need to use the correct API URL, for more information: https://github.com/webapix/mygls-sdk/wiki/Basic-usage
$account = new \Webapix\GLS\Models\Account(
   'https://api.test.mygls.hu/ParcelService.svc/json/',
   '100000004',
   'myglstest@gls-hungary.com',
   '!Myglstest2019'
);

//You need to create a Parcel object, this object contains the package and the delivery information

//Create the delivery address:
$deliveryAddress = new \Webapix\GLS\Models\Address(
   'Teszt vásárló',
   'HU',
   '1172',
   'Budapest',
   'Abaliget utca',
   '11'
);
//Set the contact information
$deliveryAddress->setContactEmail('example@example.com');
$deliveryAddress->setContactName('John Doe');
$deliveryAddress->setContactPhone('+3630123456789');

//Create the pickup address, the address of place where courier pick up the shipment.
$pickupAddress = new \Webapix\GLS\Models\Address(
   'Teszt kft.',
   'HU',
   '1138',
   'Budapest',
   'teszt utca',
   '18'
);
//Set the contact information
$pickupAddress->setContactEmail('example@example.com');
$pickupAddress->setContactName('John Doe');
$pickupAddress->setContactPhone('+3630123456789');

$parcel = (new \Webapix\GLS\Models\Parcel())
  ->setClientReference('order-2')
   ->setClientNumber('100000004')
   ->setDeliveryInfo($deliveryAddress)
   ->setPickupAddress($pickupAddress)
   ->setContent('Parcel info printed on label.')
   ->addService(new \Webapix\GLS\Services\ParcelShopDelivery('2351-CSOMAGPONT'));

//For more options please check the wiki: https://github.com/webapix/mygls-sdk/wiki/Create-a-parcel

//You need to send the request to the GLS
//We send the PrintLables request, so the GLS API will return the printable label pdf

$request = new \Webapix\GLS\Requests\PrintLabels();
$request->addParcel($parcel);


$client = new \Webapix\GLS\Client(new \GuzzleHttp\Client);

/** @var \Webapix\GLS\Responses\PrintLabels $response */
$response = $client->on($account)->request($request);
if ($response->successfull()) {

   // get the parcels information: ParcelId, ParcelNumber ...
   $response->printLabelsInfo();

   // get the original response body (it's available for every requests)
   $response->data();

   // show the pdf
   header('Content-Type: application/pdf');
   die($response->getPdf());
}

die($response->errors()->firstErrorMessage());

?>

**Comment by juhaszraymond** [comment]
Megvan a hiba! 

1 karakterrel több volt a telefonszám a kapcsolat tartónál!
Ezért el is utasította! De mondjuk adhatnának erre másik hibakódot!

->setContactPhone('+363012344444');

**Comment by zsocakave** [comment]
Gondolhatod, hogy mit éltünk át a fejlesztés során... :)
