### ISSUE TITLE
PrepareLabels method can be called by the printLabelsInfo

### ISSUE THREAD

**Issue by Martin-1182** [webapix/mygls-sdk#8]
Hello in doc. you have specified that the PrepareLabels method can be called by the printLabelsInfo () function.
But this does not work. printLabelsInfo () is undefined.
Am I making a mistake somewhere?
Well thank you

**Comment by zsocakave** [comment]
Hello Martin,

Sorry, it was a mistake in the documentation, now it's fixed.

The PrepareLabels request return with ParcelInfo objects:

    /** @var \Webapix\GLS\Models\ParcelInfo[] $parcelsInfo */
    $parcelsInfo = $response->parcelInfoList();
    // $parcelsInfo[0]->parcelId;
    // $parcelsInfo[0]->clientReference;

[Check it in the updated documentation](https://github.com/webapix/mygls-sdk/wiki/PrepareLabels)

Thanks for the comment!
