### ISSUE TITLE
Multiple labels & service pick&ship

### ISSUE THREAD

**Issue by Martin-1182** [webapix/mygls-sdk#9]
Hello, I should have the following question. I send a PrepareLabels () request to the GLS, and then when the payment passes, I send GetPrintedLabels () to download the labels. The problem is when the customer chooses the pick & ship service on one package and not on the other, or when he wants to send more packages with the pick & ship service. The request with this service is not stored in gls as prepare and only one label response is returned. with the pick & ship service and other labels will not be printed. Am I making a mistake somewhere?

**Comment by zsocakave** [comment]
Hello!

I think it is a GLS bug, in case you send multiple ID-s with GetPrintedLabels request and one of them is a pick&ship parcel, it will return only the pick&ship label (receipt). If you make it in separate calls, it will return with the correct pdf.

I will report it to GLS.
